### ISSUE TITLE
[FEATURE REQUEST] Make the DoD checklist clear

### ISSUE THREAD

**Issue by romsok24** [epiphany-platform/epiphany#2832]
Problem background:
Currently our markdown issue template includes the list of tasks that needs to assessed before the issue can be closed.
The assessment can be either _done_, _not done_ or _not applicable_
while the formula does not offer such functionality ( only single mark box is available in front of each line ).

Proposed solution:
It would be good to have it prepared in a more precise way.
For example:

```
* [ ] Changelog updated (if affected version was released)
* [ ] COMPONENTS.md updated / [ ] doesn't need to be updated
* [ ] Automated tests passed (QA pipelines)
  * [ ] apply
  * [ ] upgrade
* [ ] Case covered by automated test (if possible)
* [ ] Idempotency tested / [ ] N/A
* [ ] Documentation updated / [ ] doesn't need to be updated
* [ ] All conversations in PR resolved
* [ ] Backport tasks created / [ ] doesn't need to be backported
```

---

**DoD checklist**

- Changelog
  - [x] updated
  - [ ] not needed
- COMPONENTS.md
  - [ ] updated
  - [x] not needed
- Schema
  - [ ] updated
  - [x] not needed
- Backport tasks
  - [ ] created
  - [x] not needed
- Documentation
  - [ ] added
  - [ ] updated
  - [x] not needed
- [ ] Feature has automated tests
- [ ] Automated tests passed (QA pipelines)
  - [ ] apply
  - [ ] upgrade
- [ ] Idempotency tested
- [x] All conversations in PR resolved
- [ ] Solution meets requirements and is done according to design doc
- [ ] Usage compliant with license
